services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app
    environment:
      - ENVIRONMENT=development

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Preserve node_modules
    env_file:
      - ./frontend/.env  # Load .env into container
    depends_on:
      - backend

